name: clustering_ml_2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - attrs=24.3.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.1.1
  - dice-ml=0.11
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.31.0
  - jedi=0.19.2
  - joblib=1.4.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openssl=3.4.0
  - packaging=24.2
  - pandas=1.5.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pytz=2024.2
  - pyzmq=26.2.0
  - raiutils=0.4.2
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rpds-py=0.22.3
  - scikit-learn=1.6.0
  - scipy=1.14.1
  - setuptools=75.6.0
  - six=1.17.0
  - stack_data=0.6.3
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - cloudpickle==3.1.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.55.3
      - kiwisolver==1.4.8
      - lightgbm==4.5.0
      - llvmlite==0.43.0
      - matplotlib==3.10.0
      - numba==0.60.0
      - nvidia-nccl-cu12==2.23.4
      - pillow==11.1.0
      - pyparsing==3.2.1
      - seaborn==0.13.2
      - shap==0.46.0
      - slicer==0.0.8
      - xgboost==2.1.3
